name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: build
    env:
      GIT_NAME: ${{ secrets.GIT_NAME }}
      GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
    steps:
      - uses: actions/checkout@v2
      - name: Build and Deploy
        run: |
          npm install
          npm run build
          git config --global user.email "$GIT_EMAIL"
          git config --global user.email "$GIT_NAME"
          git add -A
          git commit -m "Deploy $(date +%Y-%m-%d-%H-%S)"
          git push -f "https://${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" main:gh-pages
